name: TestPlugin
main: TestPlugin.TestPlugin
version: 0

name: Basic
main: TestPlugin.TestPlugin
version: 1.0
author: Jadog
commands:
   basic:
      description: This is a demo command.
      usage: /<command> [player]
      permission: TestPlugin.basic
      permission-message: You don't have <permission>
      
   ignite:
      description: This is a demo command.
      usage: /<command> [player]
      permission: TestPlugin.basic
      permission-message: You don't have <permission>
      